Traceback (most recent call last):
  File "c:\users\cas\appdata\local\programs\python\python37\lib\site-packages\jupyter_cache\executors\utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "c:\users\cas\appdata\local\programs\python\python37\lib\site-packages\nbclient\client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "c:\users\cas\appdata\local\programs\python\python37\lib\site-packages\nbclient\util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "c:\users\cas\appdata\local\programs\python\python37\lib\site-packages\nbclient\util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "c:\users\cas\appdata\local\programs\python\python37\lib\asyncio\base_events.py", line 584, in run_until_complete
    return future.result()
  File "c:\users\cas\appdata\local\programs\python\python37\lib\site-packages\nbclient\client.py", line 541, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "c:\users\cas\appdata\local\programs\python\python37\lib\site-packages\nbclient\client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "c:\users\cas\appdata\local\programs\python\python37\lib\site-packages\nbclient\client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
%matplotlib inline
from ipywidgets import interactive

from lorenz import solve_lorenz
w=interactive(solve_lorenz,sigma=(0.0,50.0),rho=(0.0,50.0))
w
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[1;32m<ipython-input-3-b93d2fb2968e>[0m in [0;36m<module>[1;34m[0m
[0;32m      2[0m [1;32mfrom[0m [0mipywidgets[0m [1;32mimport[0m [0minteractive[0m[1;33m[0m[1;33m[0m[0m
[0;32m      3[0m [1;33m[0m[0m
[1;32m----> 4[1;33m [1;32mfrom[0m [0mlorenz[0m [1;32mimport[0m [0msolve_lorenz[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      5[0m [0mw[0m[1;33m=[0m[0minteractive[0m[1;33m([0m[0msolve_lorenz[0m[1;33m,[0m[0msigma[0m[1;33m=[0m[1;33m([0m[1;36m0.0[0m[1;33m,[0m[1;36m50.0[0m[1;33m)[0m[1;33m,[0m[0mrho[0m[1;33m=[0m[1;33m([0m[1;36m0.0[0m[1;33m,[0m[1;36m50.0[0m[1;33m)[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m      6[0m [0mw[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\Documents\GitHub\lucabooks\lorenz.py[0m in [0;36m<module>[1;34m[0m
[0;32m      2[0m [1;32mfrom[0m [0mmpl_toolkits[0m[1;33m.[0m[0mmplot3d[0m [1;32mimport[0m [0mAxes3D[0m[1;33m[0m[1;33m[0m[0m
[0;32m      3[0m [1;32mimport[0m [0mnumpy[0m [1;32mas[0m [0mnp[0m[1;33m[0m[1;33m[0m[0m
[1;32m----> 4[1;33m [1;32mfrom[0m [0mscipy[0m [1;32mimport[0m [0mintegrate[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      5[0m [1;33m[0m[0m
[0;32m      6[0m [1;32mdef[0m [0msolve_lorenz[0m[1;33m([0m[0msigma[0m[1;33m=[0m[1;36m10.0[0m[1;33m,[0m [0mbeta[0m[1;33m=[0m[1;36m8.[0m[1;33m/[0m[1;36m3[0m[1;33m,[0m [0mrho[0m[1;33m=[0m[1;36m28.0[0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m

[1;31mModuleNotFoundError[0m: No module named 'scipy'
ModuleNotFoundError: No module named 'scipy'

